### ISSUE TITLE
prefix argument for evil-mc-inc... and evil-mc-dec...

### ISSUE THREAD

**Issue by Dickby** [gabesoft/evil-mc-extras#2]
Hi,
`evil-numbers/inc-at-point` and `evil-numbers-dec-at-point` are accepting a prefix argument,
it would be nice to have it in the evil-mc-extras functions too.

**Comment by Dickby** [comment]
Thanks for working on this,
but i hoped for another behavior:
starting with this line:
`0 0 0 0 0`
and a cursor at every zero. The keysequence `5gl+`
gives now
`5 6 7 8 9`
i think it would be more logical if it was
`0 5 10 15 20 `
because this is what you get if you press `gl+` 5 times.
What do you think?

**Comment by gabesoft** [comment]
Actually I think you're right.  Because it's pretty easy to get the current behavior just by setting every number to the starting value.
